/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FilenameRouteImport } from './routes/$filename'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'

const FilenameRoute = FilenameRouteImport.update({
  id: '/$filename',
  path: '/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$filename' | '/api/public/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$filename' | '/api/public/upload'
  id: '__root__' | '/' | '/$filename' | '/api/public/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilenameRoute: typeof FilenameRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$filename': {
      id: '/$filename'
      path: '/$filename'
      fullPath: '/$filename'
      preLoaderRoute: typeof FilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilenameRoute: FilenameRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
