/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XRouteImport } from './routes/x'
import { Route as TempmailRouteImport } from './routes/tempmail'
import { Route as ShsdbConsoleRouteImport } from './routes/shsdb-console'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as NoteRouteImport } from './routes/note'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MainRouteImport } from './routes/main'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as DbConsoleRouteImport } from './routes/db-console'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as FilenameRouteImport } from './routes/$filename'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NoteIndexRouteImport } from './routes/note.index'
import { Route as ShsdbCreateRouteImport } from './routes/shsdb.create'
import { Route as ShsdbIdRouteImport } from './routes/shsdb.$id'
import { Route as NoteNoteIdRouteImport } from './routes/note.$noteId'
import { Route as DbCreateRouteImport } from './routes/db.create'
import { Route as DbIdRouteImport } from './routes/db.$id'
import { Route as ApiXUserRouteImport } from './routes/api/x/user'
import { Route as ApiXTweetsRouteImport } from './routes/api/x/tweets'
import { Route as ApiXDownloadRouteImport } from './routes/api/x/download'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as ApiMessagesSendRouteImport } from './routes/api/messages/send'
import { Route as ApiMessagesRegisterRouteImport } from './routes/api/messages/register'
import { Route as ApiMessagesPublickeyRouteImport } from './routes/api/messages/publickey'
import { Route as ApiMessagesListRouteImport } from './routes/api/messages/list'
import { Route as ApiIgUserRouteImport } from './routes/api/ig/user'

const XRoute = XRouteImport.update({
  id: '/x',
  path: '/x',
  getParentRoute: () => rootRouteImport,
} as any)
const TempmailRoute = TempmailRouteImport.update({
  id: '/tempmail',
  path: '/tempmail',
  getParentRoute: () => rootRouteImport,
} as any)
const ShsdbConsoleRoute = ShsdbConsoleRouteImport.update({
  id: '/shsdb-console',
  path: '/shsdb-console',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteRoute = NoteRouteImport.update({
  id: '/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const DbConsoleRoute = DbConsoleRouteImport.update({
  id: '/db-console',
  path: '/db-console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const FilenameRoute = FilenameRouteImport.update({
  id: '/$filename',
  path: '/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteIndexRoute = NoteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoteRoute,
} as any)
const ShsdbCreateRoute = ShsdbCreateRouteImport.update({
  id: '/shsdb/create',
  path: '/shsdb/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ShsdbIdRoute = ShsdbIdRouteImport.update({
  id: '/shsdb/$id',
  path: '/shsdb/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteNoteIdRoute = NoteNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => NoteRoute,
} as any)
const DbCreateRoute = DbCreateRouteImport.update({
  id: '/db/create',
  path: '/db/create',
  getParentRoute: () => rootRouteImport,
} as any)
const DbIdRoute = DbIdRouteImport.update({
  id: '/db/$id',
  path: '/db/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXUserRoute = ApiXUserRouteImport.update({
  id: '/api/x/user',
  path: '/api/x/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXTweetsRoute = ApiXTweetsRouteImport.update({
  id: '/api/x/tweets',
  path: '/api/x/tweets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiXDownloadRoute = ApiXDownloadRouteImport.update({
  id: '/api/x/download',
  path: '/api/x/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesSendRoute = ApiMessagesSendRouteImport.update({
  id: '/api/messages/send',
  path: '/api/messages/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRegisterRoute = ApiMessagesRegisterRouteImport.update({
  id: '/api/messages/register',
  path: '/api/messages/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesPublickeyRoute = ApiMessagesPublickeyRouteImport.update({
  id: '/api/messages/publickey',
  path: '/api/messages/publickey',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesListRoute = ApiMessagesListRouteImport.update({
  id: '/api/messages/list',
  path: '/api/messages/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIgUserRoute = ApiIgUserRouteImport.update({
  id: '/api/ig/user',
  path: '/api/ig/user',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/convert': typeof ConvertRoute
  '/db-console': typeof DbConsoleRoute
  '/instagram': typeof InstagramRoute
  '/main': typeof MainRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/note': typeof NoteRouteWithChildren
  '/owner': typeof OwnerRoute
  '/shsdb-console': typeof ShsdbConsoleRoute
  '/tempmail': typeof TempmailRoute
  '/x': typeof XRoute
  '/db/$id': typeof DbIdRoute
  '/db/create': typeof DbCreateRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/shsdb/$id': typeof ShsdbIdRoute
  '/shsdb/create': typeof ShsdbCreateRoute
  '/note/': typeof NoteIndexRoute
  '/api/ig/user': typeof ApiIgUserRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/publickey': typeof ApiMessagesPublickeyRoute
  '/api/messages/register': typeof ApiMessagesRegisterRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/x/download': typeof ApiXDownloadRoute
  '/api/x/tweets': typeof ApiXTweetsRoute
  '/api/x/user': typeof ApiXUserRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/convert': typeof ConvertRoute
  '/db-console': typeof DbConsoleRoute
  '/instagram': typeof InstagramRoute
  '/main': typeof MainRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/owner': typeof OwnerRoute
  '/shsdb-console': typeof ShsdbConsoleRoute
  '/tempmail': typeof TempmailRoute
  '/x': typeof XRoute
  '/db/$id': typeof DbIdRoute
  '/db/create': typeof DbCreateRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/shsdb/$id': typeof ShsdbIdRoute
  '/shsdb/create': typeof ShsdbCreateRoute
  '/note': typeof NoteIndexRoute
  '/api/ig/user': typeof ApiIgUserRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/publickey': typeof ApiMessagesPublickeyRoute
  '/api/messages/register': typeof ApiMessagesRegisterRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/x/download': typeof ApiXDownloadRoute
  '/api/x/tweets': typeof ApiXTweetsRoute
  '/api/x/user': typeof ApiXUserRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$filename': typeof FilenameRoute
  '/convert': typeof ConvertRoute
  '/db-console': typeof DbConsoleRoute
  '/instagram': typeof InstagramRoute
  '/main': typeof MainRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/note': typeof NoteRouteWithChildren
  '/owner': typeof OwnerRoute
  '/shsdb-console': typeof ShsdbConsoleRoute
  '/tempmail': typeof TempmailRoute
  '/x': typeof XRoute
  '/db/$id': typeof DbIdRoute
  '/db/create': typeof DbCreateRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/shsdb/$id': typeof ShsdbIdRoute
  '/shsdb/create': typeof ShsdbCreateRoute
  '/note/': typeof NoteIndexRoute
  '/api/ig/user': typeof ApiIgUserRoute
  '/api/messages/list': typeof ApiMessagesListRoute
  '/api/messages/publickey': typeof ApiMessagesPublickeyRoute
  '/api/messages/register': typeof ApiMessagesRegisterRoute
  '/api/messages/send': typeof ApiMessagesSendRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/x/download': typeof ApiXDownloadRoute
  '/api/x/tweets': typeof ApiXTweetsRoute
  '/api/x/user': typeof ApiXUserRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$filename'
    | '/convert'
    | '/db-console'
    | '/instagram'
    | '/main'
    | '/messages'
    | '/more'
    | '/note'
    | '/owner'
    | '/shsdb-console'
    | '/tempmail'
    | '/x'
    | '/db/$id'
    | '/db/create'
    | '/note/$noteId'
    | '/shsdb/$id'
    | '/shsdb/create'
    | '/note/'
    | '/api/ig/user'
    | '/api/messages/list'
    | '/api/messages/publickey'
    | '/api/messages/register'
    | '/api/messages/send'
    | '/api/public/upload'
    | '/api/x/download'
    | '/api/x/tweets'
    | '/api/x/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$filename'
    | '/convert'
    | '/db-console'
    | '/instagram'
    | '/main'
    | '/messages'
    | '/more'
    | '/owner'
    | '/shsdb-console'
    | '/tempmail'
    | '/x'
    | '/db/$id'
    | '/db/create'
    | '/note/$noteId'
    | '/shsdb/$id'
    | '/shsdb/create'
    | '/note'
    | '/api/ig/user'
    | '/api/messages/list'
    | '/api/messages/publickey'
    | '/api/messages/register'
    | '/api/messages/send'
    | '/api/public/upload'
    | '/api/x/download'
    | '/api/x/tweets'
    | '/api/x/user'
  id:
    | '__root__'
    | '/'
    | '/$filename'
    | '/convert'
    | '/db-console'
    | '/instagram'
    | '/main'
    | '/messages'
    | '/more'
    | '/note'
    | '/owner'
    | '/shsdb-console'
    | '/tempmail'
    | '/x'
    | '/db/$id'
    | '/db/create'
    | '/note/$noteId'
    | '/shsdb/$id'
    | '/shsdb/create'
    | '/note/'
    | '/api/ig/user'
    | '/api/messages/list'
    | '/api/messages/publickey'
    | '/api/messages/register'
    | '/api/messages/send'
    | '/api/public/upload'
    | '/api/x/download'
    | '/api/x/tweets'
    | '/api/x/user'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilenameRoute: typeof FilenameRoute
  ConvertRoute: typeof ConvertRoute
  DbConsoleRoute: typeof DbConsoleRoute
  InstagramRoute: typeof InstagramRoute
  MainRoute: typeof MainRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  NoteRoute: typeof NoteRouteWithChildren
  OwnerRoute: typeof OwnerRoute
  ShsdbConsoleRoute: typeof ShsdbConsoleRoute
  TempmailRoute: typeof TempmailRoute
  XRoute: typeof XRoute
  DbIdRoute: typeof DbIdRoute
  DbCreateRoute: typeof DbCreateRoute
  ShsdbIdRoute: typeof ShsdbIdRoute
  ShsdbCreateRoute: typeof ShsdbCreateRoute
  ApiIgUserRoute: typeof ApiIgUserRoute
  ApiMessagesListRoute: typeof ApiMessagesListRoute
  ApiMessagesPublickeyRoute: typeof ApiMessagesPublickeyRoute
  ApiMessagesRegisterRoute: typeof ApiMessagesRegisterRoute
  ApiMessagesSendRoute: typeof ApiMessagesSendRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiXDownloadRoute: typeof ApiXDownloadRoute
  ApiXTweetsRoute: typeof ApiXTweetsRoute
  ApiXUserRoute: typeof ApiXUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/x': {
      id: '/x'
      path: '/x'
      fullPath: '/x'
      preLoaderRoute: typeof XRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tempmail': {
      id: '/tempmail'
      path: '/tempmail'
      fullPath: '/tempmail'
      preLoaderRoute: typeof TempmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shsdb-console': {
      id: '/shsdb-console'
      path: '/shsdb-console'
      fullPath: '/shsdb-console'
      preLoaderRoute: typeof ShsdbConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note': {
      id: '/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db-console': {
      id: '/db-console'
      path: '/db-console'
      fullPath: '/db-console'
      preLoaderRoute: typeof DbConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$filename': {
      id: '/$filename'
      path: '/$filename'
      fullPath: '/$filename'
      preLoaderRoute: typeof FilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/': {
      id: '/note/'
      path: '/'
      fullPath: '/note/'
      preLoaderRoute: typeof NoteIndexRouteImport
      parentRoute: typeof NoteRoute
    }
    '/shsdb/create': {
      id: '/shsdb/create'
      path: '/shsdb/create'
      fullPath: '/shsdb/create'
      preLoaderRoute: typeof ShsdbCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shsdb/$id': {
      id: '/shsdb/$id'
      path: '/shsdb/$id'
      fullPath: '/shsdb/$id'
      preLoaderRoute: typeof ShsdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdRouteImport
      parentRoute: typeof NoteRoute
    }
    '/db/create': {
      id: '/db/create'
      path: '/db/create'
      fullPath: '/db/create'
      preLoaderRoute: typeof DbCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/db/$id': {
      id: '/db/$id'
      path: '/db/$id'
      fullPath: '/db/$id'
      preLoaderRoute: typeof DbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/user': {
      id: '/api/x/user'
      path: '/api/x/user'
      fullPath: '/api/x/user'
      preLoaderRoute: typeof ApiXUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/tweets': {
      id: '/api/x/tweets'
      path: '/api/x/tweets'
      fullPath: '/api/x/tweets'
      preLoaderRoute: typeof ApiXTweetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/x/download': {
      id: '/api/x/download'
      path: '/api/x/download'
      fullPath: '/api/x/download'
      preLoaderRoute: typeof ApiXDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/send': {
      id: '/api/messages/send'
      path: '/api/messages/send'
      fullPath: '/api/messages/send'
      preLoaderRoute: typeof ApiMessagesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/register': {
      id: '/api/messages/register'
      path: '/api/messages/register'
      fullPath: '/api/messages/register'
      preLoaderRoute: typeof ApiMessagesRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/publickey': {
      id: '/api/messages/publickey'
      path: '/api/messages/publickey'
      fullPath: '/api/messages/publickey'
      preLoaderRoute: typeof ApiMessagesPublickeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/list': {
      id: '/api/messages/list'
      path: '/api/messages/list'
      fullPath: '/api/messages/list'
      preLoaderRoute: typeof ApiMessagesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ig/user': {
      id: '/api/ig/user'
      path: '/api/ig/user'
      fullPath: '/api/ig/user'
      preLoaderRoute: typeof ApiIgUserRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NoteRouteChildren {
  NoteNoteIdRoute: typeof NoteNoteIdRoute
  NoteIndexRoute: typeof NoteIndexRoute
}

const NoteRouteChildren: NoteRouteChildren = {
  NoteNoteIdRoute: NoteNoteIdRoute,
  NoteIndexRoute: NoteIndexRoute,
}

const NoteRouteWithChildren = NoteRoute._addFileChildren(NoteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilenameRoute: FilenameRoute,
  ConvertRoute: ConvertRoute,
  DbConsoleRoute: DbConsoleRoute,
  InstagramRoute: InstagramRoute,
  MainRoute: MainRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  NoteRoute: NoteRouteWithChildren,
  OwnerRoute: OwnerRoute,
  ShsdbConsoleRoute: ShsdbConsoleRoute,
  TempmailRoute: TempmailRoute,
  XRoute: XRoute,
  DbIdRoute: DbIdRoute,
  DbCreateRoute: DbCreateRoute,
  ShsdbIdRoute: ShsdbIdRoute,
  ShsdbCreateRoute: ShsdbCreateRoute,
  ApiIgUserRoute: ApiIgUserRoute,
  ApiMessagesListRoute: ApiMessagesListRoute,
  ApiMessagesPublickeyRoute: ApiMessagesPublickeyRoute,
  ApiMessagesRegisterRoute: ApiMessagesRegisterRoute,
  ApiMessagesSendRoute: ApiMessagesSendRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiXDownloadRoute: ApiXDownloadRoute,
  ApiXTweetsRoute: ApiXTweetsRoute,
  ApiXUserRoute: ApiXUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
